CONFIG = {
    'image_h': 640,
    'image_w': 640,
    'backbone_channels': 512,
    'd_model': 256,
    'num_queries': 25,
    'encoder_layers': 4,
    'decoder_layers': 4,
    'encoder_attn_heads': 8,
    'decoder_attn_heads': 8,
    'ff_inner_dim': 2048,
    'dropout_prob': 0.1,
    'cls_cost_weight': 1.0,
    'l1_cost_weight': 5.0,
    'giou_cost_weight': 2.0,
    'bg_class_weight': 0.1,
    'nms_threshold': 0.5,
    'freeze_backbone': False,
}